### ISSUE TITLE
First point and power of 2

### ISSUE THREAD

**Issue by tupui** [DavidWalz/sobol#2]
Hi 👋 Pamphile from SciPy and the author and maintainer of `scipy.stats.qmc` (thanks for the note in the readme).

Sobol' (don't forget the `'` which is part of the name) sequences need particular attention with 2 points: do not thin the sequence and only use a number of sample which is a power of 2. If you don't, then balance properties are lost and the sequence is failing to deliver its nice convergence rate.

i.e. in the readme you should only show samples of size of a power of 2. And also fix the fact that the sequence does not start at 0.

**Comment by DavidWalz** [comment]
Hi Pamphile, thanks for the catch! I updated the example. `skip` can be used to fast-forward the state.

**Comment by tupui** [comment]
Thanks for having a look 😃 

Skipping is a tough business. For it to be correct you must respect a few things: you can only skip a power of 2 samples. Then if you skip `2**M` samples, you can only sample `2**n` with `n<M`. Otherwise you don't have a Sobol' sequence and you will have an imbalanced sample.

Also your example still shows that the first point is not 0 which is a problem because then the point `2**n` does not belong to this set of sample but to the next power of 2. You would have better convergence performance by removing the last point then.

See https://arxiv.org/abs/2008.08051 for more details on these points.
